"""LEGACY DEMO RUNNER

Use run_FALCON.py for new universal datasets. This file preserves the
original RAMOS/THP1 demo configuration and still contains LNP-specific
example columns such as Ionizable_lipid and Helper_lipid.
"""


from falcon_engine.utilities import extract_training_data, init_pipeline, save_pipeline, startup_banner
from falcon_engine.run_Model_Selection import run_Model_Selection 
from falcon_engine.run_optimization import run_optimization_pipeline
from falcon_engine import learning_curve
import pandas as pd
import pickle 
from falcon_engine.utilities import print_slowly
from falcon_engine.run_mantis_formatter import run_mantis_formatter_pipeline
import warnings
import time

warnings.filterwarnings("ignore")

"""
run_FALCON script

- Main script for execution of FALCON computational pipeline: 
  - Part 1 (surrogate model training): trains XGBoost models to predict LNP transfection in specified cell types
  - Part 2 (optimization): leverages ML-guided algorithms to suggest LNP compositions for experimental testing.
  - Part 3 (optional add on): formats optimized compositions for MANTIS liquid handler input 
  - note: each part can be re-run independently (provided previous runs exist) by setting corresponding flags to True or False. 
- To run: follow 4 steps in main function to configure pipeline, then run script
  - Adjustable parameters:
    - Optimization method(s): DA, BO, NSGAII, or i-optimal (opt_method)
    - Number of formulations to generate (num_formulations)
    - Restrictions on suggested formulation compositions (raw_suggestion_bounds, diversity_threshold)
    - Cell types for maximization and minimization objectives (MAX_cell_targets, MIN_cell_targets)
    - Dataset name and path for training data (DATASET_NAME)
    - Run name for saving trained models and optimized formulations (RUN_NAME)
    - input_params for model training (input_param_names)
- Output files exported to RUN_NAME folder (saved trained models, optimized formulations, model diagnostics, etc.)

"""

def main():
  ############### STEP 1: SEARCH CONFIGURATION #########################
  
  opt_methods = ['DA', 'BO', 'NSGAII', 'i-optimal'] # DA, BO, NSGAII, i-optimal

  num_formulations = 6 #number of formulations to be generated by each optimization method 

  raw_suggestion_bounds = {
        'NP_ratio': (2, 20),
        'PEG_PEG+Chol': (0.1, 20),
        'IL+HL':(20,90),
        'HL_IL+HL':(0,80),
        }
    
  diversity_threshold = 0.05 #SHAP-weighted diversity threshold: how diverse do you want your suggestions to be? ([0,1], 1 is more diverse)
  # can use cooling schedule to ecnourage high exploration in early iterations 
  #ex. iter 1: 0.15, iter 2: 0.10, iter 3: 0.075, iter 4: 0.05, etc... 

  ############### STEP 2: CELL TYPES AND OBJECTIVE CONFIGURATION #######
  # ex. cell types used in manuscript ['RAMOS','DC','3T3','C2C12'] 
  MAX_cell_targets = ['RAMOS'] # set as empty list if no maximization is desired (not '')
  MIN_cell_targets = ['THP1'] # set as empty list if no minimization is desired (not '') 
  
  nLnLE_floor = -100 #minimum cutoff for output values. nLnLE values are already blank normalized, so not needed. 

  #model training will be done for each cell type in this list
  #DA and BO will only use first cell type in this list for single-objective maximization, NSGAII will consisder all cell types
  cell_type_list = MAX_cell_targets + MIN_cell_targets 

  ################ STEP 3: LOAD AND SAVE PATH CONFIGURATION #############
  RUN_NAME = "Demo_Results" #Give a name for run folder to save any trained models
  DATASET_NAME = 'Demo_Norm_RAMOS_THP1_Single_Dual_Objective_4ITER_MC3_DSPC' #Name of the csv file, used to extract training data

  ################ STEP 4: PIPELINE COMPONENTS CONFIGURATION #############
  run_model_training = True # set true unless model is already trained and saved in output folder
  run_optimization = False  # set true unless de novo formulation generation is not desired 
  run_mantis_formatter = False # set true if you want to format the optimized formulations for MANTIS (liquid handler) input

  ########################################################################
  pipeline_start_time = time.time()
  training_runtime = None
  optimization_runtime = None
  data_file_path = f'datasets/{DATASET_NAME}.csv' #Path to the dataset to be used for training

  # Input_Params (features to be used for model training and prediction) 
  # remove for now - 'NP_ratio',
  input_param_names = ['NP_ratio','IL+HL','HL_IL+HL','PEG_PEG+Chol']

  if run_model_training == True:  
    training_start = time.time()
    for c in cell_type_list:   #Loop through model training for each cell type of interest
      pipeline_path = f'output/{RUN_NAME}/{c}/Pipeline_dict.pkl'
      #Initialize new model pipeline
      pipeline_dict = init_pipeline(pipeline_path = pipeline_path,
                                      RUN_NAME=RUN_NAME,
                                      input_param_names=input_param_names,
                                      cell = c,
                                      model_list= [ 'kNN', 'PLS', 'lasso', 'ENet', 'MLR', 'DT'], # 'XGB', 'LGBM','RF', 'ET', 'GBR', 'HGBR', 'ADA', 'MLP', 'SVR',  #List of models to be trained (e.g., XGB, LGBM, RF, ET, GBR, HGBR, ADA, MLP, SVR, kNN, PLS, lasso, ENet, MLR)
                                      param_type = 'percent',
                                      data_file_path=data_file_path,
                                      prefix='nLnLE_', #prefix for target output in the dataset
                                      output_floor=nLnLE_floor,
                                      N_CV=5)
      pipeline_dict, _, _, _= extract_training_data(pipeline_dict) 
      pipeline_dict, _, _, _ = run_Model_Selection(pipeline_dict)
      pipeline_dict = learning_curve.get_learning_curve(pipeline_dict, refined = False)
      save_pipeline(pipeline=pipeline_dict, path = pipeline_path, step = 'FINAL SAVE')  
    training_runtime = time.time() - training_start
  
  if run_optimization == True:
    optimization_start = time.time()
    optimized_formulations = pd.DataFrame()
    optimized_formulations= run_optimization_pipeline(opt_methods, num_formulations, MAX_cell_targets, MIN_cell_targets, RUN_NAME, diversity_threshold,
                                                  raw_suggestion_bounds)

    #export optimized_formulations as pkl
    with open(f'output/{RUN_NAME}/raw_suggested_formulations.pkl', 'wb') as f:
      pickle.dump(optimized_formulations, f)

    df_existing = pd.read_csv(data_file_path)
    last_label = df_existing['Formula_label'].max() 
    last_iter = df_existing['Iter'].max()
    last_ionizable = df_existing['Ionizable_lipid'].dropna().iloc[-1]
    last_helper = df_existing['Helper_lipid'].dropna().iloc[-1]

    cols = df_existing.columns.tolist()
    output_file_path = f'output/{RUN_NAME}/optimized_formulation_dataset.csv'

    print_slowly("\n\n--- EXPORTING ALL GENERATED FORMULATIONS to csv ---")

    # Create rows to append
    new_rows = []
    for i, row in optimized_formulations.iterrows():
        new_row = {
            'Formula_label': last_label + i + 1,
            'Iter': last_iter + 1,
            'Opt_Method': row['opt_method'],
            'Ionizable_lipid': last_ionizable,
            'Helper_lipid': last_helper,
        }
        for param in input_param_names:
            new_row[param] = row[param]
        new_rows.append(new_row)

    # Create DataFrame from new rows
    df_new = pd.DataFrame(new_rows)

    # Create full structure if needed
    df_new_full = pd.DataFrame(columns=cols)
    df_new_full = pd.concat([df_new_full, df_new], ignore_index=True)

    # Combine with existing data and save
    df_combined = pd.concat([df_existing, df_new_full], ignore_index=True)
    df_combined.to_csv(output_file_path, index=False)
    print(f"Optimized formulations saved to {output_file_path}")
    optimization_runtime = time.time() - optimization_start

  pipeline_runtime = time.time() - pipeline_start_time
  print_slowly("\n\n========== PIPELINE RUNTIME SUMMARY ==========")

  if training_runtime is not None:
      print_slowly(f"Model Training: {training_runtime/60:.2f} minutes")

  if optimization_runtime is not None:
      print_slowly(f"Optimization: {optimization_runtime/60:.2f} minutes")

  print_slowly(f"Total Runtime: {pipeline_runtime/60:.2f} minutes")
  print_slowly("==============================================\n")

  if run_mantis_formatter == True:
    with open(f'output/{RUN_NAME}/raw_suggested_formulations.pkl', 'rb') as f:
      optimized_formulations = pickle.load(f)
      
    run_mantis_formatter_pipeline(RUN_NAME, input_param_names, optimized_formulations)
    import sys
    exit()
if __name__ == "__main__":
    startup_banner()
    # Run the main function
    main()
